### ISSUE TITLE
Have a direct link to a category

### ISSUE THREAD

**Issue by sangorys** [mikezimm/pivottiles7#2]
**Is your feature request related to a problem? Please describe.**
I would like to get a direct link to a category

**Describe the solution you'd like**
An url

**Describe alternatives you've considered**
No direct link

**Additional context**
NA

**Comment by mikezimm** [comment]
Basically have it so that you can pass a parameter that sets the default category

![image](https://user-images.githubusercontent.com/49648086/99980218-fcc31900-2d75-11eb-9cba-f9af6e967078.png)

**Comment by mikezimm** [comment]
@sangorys ,

## This should be included in **v1.2.0.0**... you can check that by
1. pressing the **?** in upper right
2. then select **About** page
3. then look for the version number

## The correct syntax would be:
just add **?category=Value** to your Url like this:

https://yourYour.sharepoint.com/sites/PivotTiles/?category=FindMe

![image](https://user-images.githubusercontent.com/49648086/100020224-73c7d400-2dad-11eb-9441-a4d9e6db4531.png)
