### ISSUE TITLE
Having problems adding to the custom categories list

### ISSUE THREAD

**Issue by nirmalnarayan** [mikezimm/pivottiles7#29]
For Example we have:
CAE;Airbag;SW;SB;Head;Node;;;;_High
It doesn't show the SB 

![image](https://user-images.githubusercontent.com/75451016/101091170-ceb7b300-3585-11eb-9e45-b5042667b4b3.png)

**Comment by mikezimm** [comment]
@nirmalnarayan , in this case, be sure "SB" is found in either the Page Title or Page Description (found by clicking page details gear).

Note that custom categories are Case Sensitive.
Also note that as of now, adding extra ;;;; will cause the 'Others' tab to disapear so I would not use that at this point.

Mike
