### ISSUE TITLE
Some visual glitches and hyperlinks does not work with the webPart Microsoft Form

### ISSUE THREAD

**Issue by sangorys** [mikezimm/pivottiles7#3]
When I use on the same page :

- This webPart
- Microsoft Form webPart, also Call to action webpart

I have some random bugs if Pivot-Tiles is above Microsoft Form :

- Sometimes, I have visual bugs
- Sometimes, hyperlinks do not work

See the attached picture for an example

![image](https://user-images.githubusercontent.com/544194/97032299-e0a73e80-1561-11eb-96a3-7a5175647d1a.png)

**Comment by mikezimm** [comment]
To remove the issue, just need to add Pivot Tiles into it's own section and it will not overflow other webparts.
Closing
