### ISSUE TITLE
Please elaborate documentation on errors

### ISSUE THREAD

**Issue by McDKirra** [mikezimm/pivottiles7#33]
Please elaborate documentation on errors taking into consideration that it would help others grasping for straws when troubleshooting and accessing the errors page! 

![image](https://user-images.githubusercontent.com/35781691/101177949-0c354280-3651-11eb-8f13-1c028345f9ba.png)

**Comment by mikezimm** [comment]
@McDKirra , I updated this specific error summary in v1.2.2.4.
I'll look at improving the entire panel at some point when I get time so I'll keep this open for now.
