### ISSUE TITLE
Tiles get cut off on page

### ISSUE THREAD

**Issue by McDKirra** [mikezimm/pivottiles7#6]
Only shows a quarter of them for some reason when there are webparts under. It's like overlap hides them

![image](https://user-images.githubusercontent.com/35781691/90036886-317df980-dccc-11ea-9439-917c9d7e0ff9.png)

**Comment by mikezimm** [comment]
The temporary solution is to just put it in it's own section that as preferably full-width section.

**Comment by mikezimm** [comment]
Check spfx columns and rows grid css...

**Comment by mikezimm** [comment]
We have been just adding webpart to it's own section and it seems to work just fine.  Have not had a case where this work-around does not work so closing the issue.
